### ISSUE TITLE
Setup CI / Artifact Publishing

### ISSUE THREAD

**Issue by hasheddan** [crossplane-contrib/provider-ibm-cloud#11]
### What problem are you facing?

`provider-ibm-cloud` needs to publish artifacts for users to consume.

### How could Crossplane help solve your problem?

Setup CI pipelines to publish artifacts.

**Comment by hasheddan** [comment]
@negz could you close this out when credentials are added? Looks like we are skipping publishing for now because they are not present

**Comment by pdettori** [comment]
I was able to manually run the Promote flow with success, so creds seem now to be present. I think we can close this one now. Thanks for all the help @hasheddan and @negz
