### ISSUE TITLE
Cloudant managed service is not being provisioned through ResourceController

### ISSUE THREAD

**Issue by jruano03** [crossplane-contrib/provider-ibm-cloud#22]
### What happened?
The Cloudant managed resource is not being provisioned through the ResourceController API. Other resources from the examples are working as expected.

### How can we reproduce it?
Define a ResourceInstance for Cloudant and apply it.

### What environment did it happen in?
Crossplane version: 
* Crossplane v1.0.0
* IBM Cloud Provider

**Comment by jruano03** [comment]
I have a fix for this. I can assign myself if I get the right permissions to do so.

**Comment by pdettori** [comment]
Thanks @jruano03, could you please create a PR for this ?

**Comment by jruano03** [comment]
PR has been created. Thanks for your help.
