### ISSUE TITLE
Error observed when creating a resource instance via Crossplane installed in OpenShift cluster

### ISSUE THREAD

**Issue by cg2p** [crossplane-contrib/provider-ibm-cloud#41]
### What happened?

Installed Crossplane and IBM provider to an OpenShift cluster (IBM ROKS) - all good.
Then created an instance of a IBM Cloud Database for PostgreSQL, this worked fine.
Therefore provision action is all ok, and can work with database.

But there is a side error where OpenShift reported an error generated from TraitDefinition - I don't know whether this is material to operating Crossplane in OpenShift cluster.

### How can we reproduce it?

```
# install crossplane and IBM provider in OpenShift; you will need the privileges workaround
oc new-project crossplane-system
helm repo add crossplane-alpha https://charts.crossplane.io/alpha

# in OpenShift this creates the Service Account 'crossplane' during the chart install
helm install crossplane --namespace crossplane-system crossplane-alpha/crossplane --set alpha.oam.enabled=true

# add privilege to this service account
oc adm policy add-scc-to-user privileged -z crossplane -n crossplane-system
curl -sL https://raw.githubusercontent.com/crossplane/crossplane/release-0.14/install.sh | sh
sudo mv kubectl-crossplane /usr/local/bin
kubectl crossplane --help
kubectl crossplane install provider crossplane/provider-ibm-cloud:alpha

# Using an IBM Cloud account with permissions to manage IBM Cloud Services:
if [[ -z "${IBMCLOUD_API_KEY}" ]]; then
  echo "*** Generating new APIKey"
  IBMCLOUD_API_KEY=$(ibmcloud iam api-key-create provider-ibm-cloud-key -d "Key for Crossplane Provider IBM Cloud" | grep "API Key" | awk '{ print $3 }')
fi

kubectl create secret generic provider-ibm-cloud-secret --from-literal=credentials=${IBMCLOUD_API_KEY} -n crossplane-system

# We will create the following ProviderConfig object to configure credentials for IBM Cloud Provider:
cat <<EOF | kubectl apply -f -
apiVersion: ibmcloud.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: ibm-cloud
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-ibm-cloud-secret
      key: credentials
  region: us-south
EOF

# add privilege to this service account
oc adm policy add-scc-to-user privileged -z provider-ibm-cloud-e0a75509c392 -n crossplane-system

# Create a resource of Kind supported by the IBM Cloud provider
apiVersion: resourcecontrollerv2.ibmcloud.crossplane.io/v1alpha1
kind: ResourceInstance
metadata:
  name: postgres-via-crossplane
spec:
  forProvider:
    name: postgres-via-crossplane
    target: us-south
    resourceGroupName: default
    serviceName: databases-for-postgresql
    resourcePlanName: standard
    tags:
      - dev
    parameters:
      members_disk_allocation_mb: 32768
  providerConfigRef:
    name: ibm-cloud
```
*Steps to reproduce*
- apply the above ResourceInstance (this work and db provisions in IBM Cloud)
- in OpenShift console, go to `crossplane-system' Project > Events

Error event:
TD manualscalertraits.core.oam.dev
(generated from TraitDefinition)
"cannot generate OpenAPI v3 JSON schema for capability manualscalertraits.core.oam.dev: capability manualscalertraits.core.oam.dev doesn't contain section `parameter`"

- yaml
```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  annotations:
    meta.helm.sh/release-name: crossplane
    meta.helm.sh/release-namespace: crossplane-system
  selfLink: >-
    /apis/core.oam.dev/v1alpha2/namespaces/crossplane-system/traitdefinitions/manualscalertraits.core.oam.dev
  resourceVersion: '11275488'
  name: manualscalertraits.core.oam.dev
  uid: a7d3a994-5212-4153-817e-b1c991f60e71
  creationTimestamp: '2021-04-29T00:50:55Z'
  generation: 1
  managedFields:
    - apiVersion: core.oam.dev/v1alpha2
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/managed-by': {}
        'f:spec':
          .: {}
          'f:definitionRef':
            .: {}
            'f:name': {}
          'f:workloadRefPath': {}
      manager: Go-http-client
      operation: Update
      time: '2021-04-29T00:50:55Z'
    - apiVersion: core.oam.dev/v1alpha2
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
      manager: a7d3a994-5212-4153-817e-b1c991f60e71
      operation: Update
      time: '2021-04-29T00:50:55Z'
  namespace: crossplane-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  definitionRef:
    name: manualscalertraits.core.oam.dev
  workloadRefPath: spec.workloadRef
status:
  conditions:
    - lastTransitionTime: '2021-04-29T00:50:55Z'
      message: >-
        cannot store capability manualscalertraits.core.oam.dev in ConfigMap:
        cannot generate OpenAPI v3 JSON schema for capability
        manualscalertraits.core.oam.dev: capability
        manualscalertraits.core.oam.dev doesn't contain section `parameter`
      reason: ReconcileError
      status: 'False'
      type: Synced
```

### What environment did it happen in?

* kubectl crossplane --version
v0.14.0

* oc version
Client Version: 4.5.35
Server Version: 4.5.37
Kubernetes Version: v1.18.3+cdb0358

* kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"297a4ac4250237ed5aed54e916ec7b88fda61bbe", GitTreeState:"clean", BuildDate:"2021-03-06T07:17:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+cdb0358", GitCommit:"cdb0358", GitTreeState:"clean", BuildDate:"2021-03-27T03:40:11Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by pdettori** [comment]
Hi @cg2p , it seems this with an older version of Crossplane, we are currently at release v1.2.0. We have published a [medium blog](https://dettori.medium.com/build-event-driven-applications-with-knative-and-crossplane-8c3fd1a50f6) providing a link to [instructions to install Crossplane in OpenShift](https://github.com/pdettori/crossplane-knative-examples/tree/main/openshift). Could you please try with these instructions ?

**Comment by cg2p** [comment]
Fixed.

The Helm install of Crossplane needs to set runAsUser and runAsGroup to null for both `securityContextRBACManager` and `securityContextCrossplane` in order to pass through the appropriate values of the user id.

`helm install crossplane --namespace crossplane-system crossplane-stable/crossplane --set securityContextCrossplane.runAsUser=null --set securityContextCrossplane.runAsGroup=null --set securityContextRBACManager.runAsUser=null --set securityContextRBACManager.runAsGroup=null`

The [instructions to install Crossplane in OpenShift](https://github.com/pdettori/crossplane-knative-examples/tree/main/openshift) can therefore be updated @pdettori

**Comment by pdettori** [comment]
Thank you @cg2p, good catch, I will update
