### ISSUE TITLE
Guidance on how to create custom composition of resources on IBM Cloud

### ISSUE THREAD

**Issue by cg2p** [crossplane-contrib/provider-ibm-cloud#42]
### What problem are you facing?

There are a set of examples for creating various custom resources in relation to Compositions [here](https://github.com/crossplane-contrib/provider-ibm-cloud/tree/master/examples/composition) in IBM Cloud.

There is documentation at [crossplane.io](https://crossplane.io/docs/v1.2/concepts/composition.html) on this, but it also does not outline the steps.

### How could Crossplane help solve your problem?

Could a README be added that explains the process to create the composition and outcome expected, including checks for success e.g. `kubectl describe ...` ?

With this IBM Cloud example explained, that would give as guide to further help understand this Crossplane concept.

**Comment by pdettori** [comment]
Closing as old issue
