### ISSUE TITLE
I can not get the expected managed resource.

### ISSUE THREAD

**Issue by dongwangdw** [crossplane-contrib/provider-ibm-cloud#50]
I setup the ibm provider accroding the readme.
And I deployed files in examples/composition:
definition.yaml
composition.yaml
claim.yaml.

But the status of composite resource is always ready.
I describe it and found two other resources:  ResourceInstance and 

I described ResourceInstance and got errors:
```
Warning  CannotCreateExternalResource  3s (x25 over 11m)  managed/resourceinstance.resourcecontrollerv2.ibmcloud.crossplane.io  error creating ResourceInstance: error getting resource group ID: could not find resource group id
```
managed/resourcekey.resourcecontrollerv2.ibmcloud.crossplane.io  could not create ResourceKey: createResourceKeyOptions failed validation:
Key: 'CreateResourceKeyOptions.Source' Error:Field validation for 'Source' failed on the 'required' tag
  Warning  CannotResolveResourceReferences  73s (x32 over 16m)  managed/resourcekey.resourcecontrollerv2.ibmcloud.crossplane.io  cannot resolve references: spec.forProvider.Source: referenced field was empty (referenced resource may not yet be ready)
```

These two resources should be reconciled according composite resouce or claim.
I can not understand if I missed any configure?
Please help,

**Comment by pdettori** [comment]
Hi @dongwangdw thank you for trying the Crossplane provider for IBM Cloud. It looks like the particular example you are trying (examples/composition/composition.yaml ) is using `resourceGroupName: default` and you probably do not have a resource group with that name. You can either edit that line in the YAML to use a name for a resource group that you have in your account or delete that line (in the latter case the provider will try to find the name for the default resource group, if you have one in your account and you have IAM permission for using it). You should then delete the resource claim and / or composite resource and re-apply the composition and try again from there.

**Comment by dongwangdw** [comment]
@pdettori Thanks for the info. It worked when I removed the ```resourceGroupName```.

Can we create k8s cluster resource currently, no?

**Comment by pdettori** [comment]
Do you mean creating k8s clusters? Or creating resources like containers in the k8s cluster where we are running the provider?

**Comment by dongwangdw** [comment]
sorry for the late response. we are at different timezone. 
Yes, I did not see any cluster like API. Or maybe I missed it, please point it to me.

**Comment by pdettori** [comment]
There is currently no support for the IKS or ROKS service on IBM Cloud, that is a feature on our list. If you need kubernetes on other cloud platforms check the other providers.
