### ISSUE TITLE
Tag v0.6.0 for new resources.

### ISSUE THREAD

**Issue by nlamirault** [crossplane-contrib/provider-ibm-cloud#75]
### What problem are you facing?

Could you provide a new tag (v0.6.0) to use new resources, like :+1: 

```
unable to recognize "STDIN": no matches for kind "Cluster" in version "container.containerv2.ibmcloud.crossplane.io/v1alpha1"
unable to recognize "STDIN": no matches for kind "Subnet" in version "vpcv1.ibmcloud.crossplane.io/v1alpha1"
unable to recognize "STDIN": no matches for kind "VPC" in version "vpcv1.ibmcloud.crossplane.io/v1alpha1"
```

**Comment by pdettori** [comment]
Hi @nlamirault thank you for your interest in the IBM cloud provider. Will look into creating a new release hopefully some time next week.

**Comment by pdettori** [comment]
v0.0.6 release has been published

**Comment by nlamirault** [comment]
@pdettori prefer v0.6.0 instead of v0.0.6 ...

**Comment by nlamirault** [comment]
@pdettori prefer v0.6.0 instead of v0.0.6 ...

**Comment by pdettori** [comment]
Thanks @nlamirault, my mistake, I have re-tagged and updated the release and docker images.
